name: Code Quality Checks

on:
  push:
    branches-ignore: []
  pull_request:
    branches-ignore: []

jobs:
  strategy:
    matrix:
      node-version: [20.x]
  lint-and-format:
    name: Lint & Format Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout/@v4
        with:
          fetch-depth: 0
      - name: Download npm Dependencies
        with:
          node-version: 20
        run: npm install
      - name: Cache npm Dependencies
        with:
          node-version: 20
          cache: "npm"
      - name: Run ESLint
        run: npx eslint ./**
      - name: Run Prettier
        run: npx prettier . --write
